### ISSUE TITLE
vos2midi not working

### ISSUE THREAD

**Issue by garyakimoto** [ReVanTis/VosDroid#3]
I open it and just a "new button" and nothing else

**Comment by ReVanTis** [comment]
Hi @garyakimoto ,
This was a student project I did many years ago and has been abandoned since then.
It was built based on vos2midi which was a result of reverse engineering of the vos format.
I guess the piece left from this project that's still useful is [the parser code](https://github.com/ReVanTis/VosDroid/blob/master/VosDroidLibrary/src/main/java/com/revantis/vosdroid/lib/VosParser.java) (which was a java translation from vos2midi) that parses vos format.
Hope this could provide some information for you if you are still interested.

**Comment by garyakimoto** [comment]
> Hi @garyakimoto , This was a student project I did many years ago and has been abandoned since then. It was built based on vos2midi which was a result of reverse engineering of the vos format. I guess the piece left from this project that's still useful is [the parser code](https://github.com/ReVanTis/VosDroid/blob/master/VosDroidLibrary/src/main/java/com/revantis/vosdroid/lib/VosParser.java) (which was a java translation from vos2midi) that parses vos format. Hope this could provide some information for you if you are still interested.

thank you so much

**Comment by ReVanTis** [comment]
@garyakimoto Should you need further help just let me know. I'm closing this one now just for the record ;)
